"""initial tables

Revision ID: 0c05b3eed3e6
Revises: 03525762d7b6
Create Date: 2025-12-15 09:23:48.198913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c05b3eed3e6'
down_revision: Union[str, Sequence[str], None] = '03525762d7b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('profile_picture_url', sa.Text(), nullable=True),
    sa.Column('username_sourced_from_provider', sa.Boolean(), nullable=True),
    sa.Column('display_name_sourced_from_provider', sa.Boolean(), nullable=True),
    sa.Column('profile_pic_sourced_from_provider', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('oauth_accounts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.Enum('x', name='oauthprovider'), nullable=False),
    sa.Column('provider_user_id', sa.Text(), nullable=False),
    sa.Column('provider_username', sa.Text(), nullable=True),
    sa.Column('provider_display_name', sa.Text(), nullable=True),
    sa.Column('provider_profile_pic_url', sa.Text(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_provider_user'),
    sqlite_autoincrement=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oauth_accounts')
    op.drop_table('users')
    # ### end Alembic commands ###
