"""remove_unique_constraint_from_username

Revision ID: 23d24b1c5eb7
Revises: 4cb20e71c05d
Create Date: 2026-02-16 15:28:36.749145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23d24b1c5eb7'
down_revision: Union[str, Sequence[str], None] = '4cb20e71c05d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_recipes_name_desc_fts'), table_name='recipes', postgresql_using='gin')
    op.create_index('idx_recipes_name_desc_fts', 'recipes', [sa.literal_column("to_tsvector('english', coalesce(name, '') || ' ' || coalesce(description, '') || ' ' || coalesce(chefs_note, ''))")], unique=False, postgresql_using='gin')
    op.drop_constraint(op.f('users_username_key1'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_username_key1'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_index('idx_recipes_name_desc_fts', table_name='recipes', postgresql_using='gin')
    op.create_index(op.f('idx_recipes_name_desc_fts'), 'recipes', [sa.literal_column("to_tsvector('english'::regconfig, (((COALESCE(name, ''::text) || ' '::text) || COALESCE(description, ''::text)) || ' '::text) || COALESCE(chefs_note, ''::text))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
