"""add chefs note to recipe

Revision ID: 2db19c1c1b59
Revises: 42d3f8e818ef
Create Date: 2026-01-25 14:10:59.735043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2db19c1c1b59'
down_revision: Union[str, Sequence[str], None] = '42d3f8e818ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('chefs_note', sa.Text(), nullable=True))
    op.drop_index(op.f('idx_recipes_name_desc_fts'), table_name='recipes', postgresql_using='gin')
    op.create_index('idx_recipes_name_desc_fts', 'recipes', [sa.literal_column("to_tsvector('english', coalesce(name, '') || ' ' || coalesce(description, '') || ' ' || coalesce(chefs_note, ''))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_recipes_name_desc_fts', table_name='recipes', postgresql_using='gin')
    op.create_index(op.f('idx_recipes_name_desc_fts'), 'recipes', [sa.literal_column("to_tsvector('english'::regconfig, (COALESCE(name, ''::text) || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    op.drop_column('recipes', 'chefs_note')
    # ### end Alembic commands ###
