"""verify_alignment

Revision ID: 42d3f8e818ef
Revises: 97dc0fa01298
Create Date: 2026-01-12 21:10:12.258869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42d3f8e818ef'
down_revision: Union[str, Sequence[str], None] = '97dc0fa01298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types
    sa.Enum('minio', 's3', name='storage_provider').create(op.get_bind(), checkfirst=True)
    sa.Enum('image', 'video', name='media_type').create(op.get_bind(), checkfirst=True)
    sa.Enum('draft', 'published', name='recipe_status').create(op.get_bind(), checkfirst=True)

    op.alter_column('oauth_accounts', 'provider',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)
    op.alter_column('recipe_media', 'storage_provider',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Enum('minio', 's3', name='storage_provider'),
               existing_nullable=False,
               postgresql_using='storage_provider::storage_provider')
    op.alter_column('recipe_media', 'media_type',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Enum('image', 'video', name='media_type'),
               existing_nullable=False,
               postgresql_using='media_type::media_type')
    # Handle 'recipes.status' specifically to avoid default value casting issues
    op.execute("ALTER TABLE recipes ALTER COLUMN status DROP DEFAULT")
    op.alter_column('recipes', 'status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('draft', 'published', name='recipe_status'),
               existing_nullable=False,
               postgresql_using='status::recipe_status')
    op.execute("ALTER TABLE recipes ALTER COLUMN status SET DEFAULT 'draft'::recipe_status")

    op.drop_index(op.f('idx_recipes_name_desc_fts'), table_name='recipes', postgresql_using='gin')
    op.create_index('idx_recipes_name_desc_fts', 'recipes', [sa.literal_column("to_tsvector('english', coalesce(name, '') || ' ' || coalesce(description, ''))")], unique=False, postgresql_using='gin')
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index('idx_recipes_name_desc_fts', table_name='recipes', postgresql_using='gin')
    op.create_index(op.f('idx_recipes_name_desc_fts'), 'recipes', [sa.literal_column("to_tsvector('english'::regconfig, (COALESCE(name, ''::text) || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    op.alter_column('recipes', 'status',
               existing_type=sa.Enum('draft', 'published', name='recipe_status'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False,
               existing_server_default=sa.text("'''draft'''::character varying"))
    op.alter_column('recipe_media', 'media_type',
               existing_type=sa.Enum('image', 'video', name='media_type'),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    op.alter_column('recipe_media', 'storage_provider',
               existing_type=sa.Enum('minio', 's3', name='storage_provider'),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    op.alter_column('oauth_accounts', 'provider',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)
    
    # Drop enum types
    sa.Enum(name='recipe_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='media_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='storage_provider').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
