"""add cascade to user_recipe_views

Revision ID: 4cb20e71c05d
Revises: e022477fe59c
Create Date: 2026-02-09 17:08:24.221604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cb20e71c05d'
down_revision: Union[str, Sequence[str], None] = 'e022477fe59c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_recipes_name_desc_fts'), table_name='recipes', postgresql_using='gin')
    op.create_index('idx_recipes_name_desc_fts', 'recipes', [sa.literal_column("to_tsvector('english', coalesce(name, '') || ' ' || coalesce(description, '') || ' ' || coalesce(chefs_note, ''))")], unique=False, postgresql_using='gin')
    op.drop_constraint(op.f('user_recipe_views_recipe_id_fkey'), 'user_recipe_views', type_='foreignkey')
    op.drop_constraint(op.f('user_recipe_views_user_id_fkey'), 'user_recipe_views', type_='foreignkey')
    op.create_foreign_key(None, 'user_recipe_views', 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_recipe_views', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_recipe_views', type_='foreignkey')
    op.drop_constraint(None, 'user_recipe_views', type_='foreignkey')
    op.create_foreign_key(op.f('user_recipe_views_user_id_fkey'), 'user_recipe_views', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('user_recipe_views_recipe_id_fkey'), 'user_recipe_views', 'recipes', ['recipe_id'], ['id'])
    op.drop_index('idx_recipes_name_desc_fts', table_name='recipes', postgresql_using='gin')
    op.create_index(op.f('idx_recipes_name_desc_fts'), 'recipes', [sa.literal_column("to_tsvector('english'::regconfig, (((COALESCE(name, ''::text) || ' '::text) || COALESCE(description, ''::text)) || ' '::text) || COALESCE(chefs_note, ''::text))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
