"""align_models_and_db_v5

Revision ID: 97dc0fa01298
Revises: 3e785f682483
Create Date: 2026-01-12 17:39:28.992354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97dc0fa01298'
down_revision: Union[str, Sequence[str], None] = '3e785f682483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_media',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('recipe_id', sa.BigInteger(), nullable=False),
    sa.Column('recipe_uuid', sa.UUID(), nullable=True),
    sa.Column('storage_provider', sa.Enum('MINIO', 'S3', name='storage_provider', native_enum=False), nullable=False),
    sa.Column('bucket', sa.Text(), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('media_type', sa.Enum('IMAGE', 'VIDEO', name='media_type', native_enum=False), nullable=False),
    sa.Column('content_type', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('processing_error', sa.String(), nullable=True),
    sa.Column('thumbnail_small_key', sa.Text(), nullable=True),
    sa.Column('thumbnail_medium_key', sa.Text(), nullable=True),
    sa.Column('thumbnail_large_key', sa.Text(), nullable=True),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recipe_media_order', 'recipe_media', ['display_order'], unique=False)
    op.create_index('idx_recipe_media_primary', 'recipe_media', ['is_primary'], unique=False)
    op.create_index('idx_recipe_media_recipe_id', 'recipe_media', ['recipe_id'], unique=False)
    op.create_index('idx_recipe_media_type', 'recipe_media', ['media_type'], unique=False)
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('category_groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ingredient_aliases', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ingredients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('oauth_accounts', sa.Column('provider', sa.Enum('X', 'GOOGLE', name='oauthprovider', native_enum=False), nullable=True))
    # Note: Added as nullable first to avoid failure if rows exist, though we should really provide a default.
    # We can set a default if we know it.
    op.alter_column('oauth_accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('oauth_accounts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.execute("ALTER TABLE oauth_accounts DROP CONSTRAINT IF EXISTS uq_oauth_provider_user")
    op.execute("ALTER TABLE oauth_accounts DROP CONSTRAINT IF EXISTS uq_provider_user")
    op.create_unique_constraint('uq_provider_user', 'oauth_accounts', ['provider', 'provider_user_id'])
    op.alter_column('recipe_ingredients', 'recipe_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('recipe_ingredients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('recipe_photos', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('recipe_photos', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('recipe_photos', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('recipe_steps', 'recipe_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('recipe_steps', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('recipes', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('DRAFT', 'PUBLISHED', name='recipe_status', native_enum=False),
               comment=None,
               existing_comment='soft draft status: draft | published | archived',
               existing_nullable=False,
               existing_server_default=sa.text("'''draft'''::character varying"))
    op.alter_column('recipes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('recipes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_recipes_name_desc_fts'), table_name='recipes', postgresql_using='gin')
    op.create_index('idx_recipes_name_desc_fts', 'recipes', [sa.literal_column("to_tsvector('english', coalesce(name, '') || ' ' || coalesce(description, ''))")], unique=False, postgresql_using='gin')
    op.drop_index(op.f('idx_recipes_uuid'), table_name='recipes')
    op.create_index('idx_recipes_uuid', 'recipes', ['uuid'], unique=True)
    op.alter_column('units', 'unit_type',
               existing_type=postgresql.ENUM('weight', 'volume', 'count', 'other', name='unit_type'),
               type_=sa.Enum('WEIGHT', 'VOLUME', 'COUNT', 'OTHER', name='unittype', native_enum=False),
               nullable=True,
               existing_server_default=sa.text("'other'::unit_type"))
    op.alter_column('units', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_recipe_views', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('user_recipe_views', 'recipe_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('user_recipe_views', 'viewed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('user_recipe_views_user_id_fkey'), 'user_recipe_views', type_='foreignkey')
    op.drop_constraint(op.f('user_recipe_views_recipe_id_fkey'), 'user_recipe_views', type_='foreignkey')
    op.create_foreign_key(None, 'user_recipe_views', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_recipe_views', 'recipes', ['recipe_id'], ['id'])
    op.alter_column('user_saved_recipes', 'saved_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('user_saved_recipes_recipe_id_fkey'), 'user_saved_recipes', type_='foreignkey')
    op.drop_constraint(op.f('user_saved_recipes_user_id_fkey'), 'user_saved_recipes', type_='foreignkey')
    op.create_foreign_key(None, 'user_saved_recipes', 'recipes', ['recipe_id'], ['id'])
    op.create_foreign_key(None, 'user_saved_recipes', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'username_sourced_from_provider',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'display_name_sourced_from_provider',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'profile_pic_sourced_from_provider',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index('users_email_key', 'users', ['email'], unique=True)
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index('users_username_key', 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('users_username_key', table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_index('users_email_key', table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'profile_pic_sourced_from_provider',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'display_name_sourced_from_provider',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'username_sourced_from_provider',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'user_saved_recipes', type_='foreignkey')
    op.drop_constraint(None, 'user_saved_recipes', type_='foreignkey')
    op.create_foreign_key(op.f('user_saved_recipes_user_id_fkey'), 'user_saved_recipes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('user_saved_recipes_recipe_id_fkey'), 'user_saved_recipes', 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_saved_recipes', 'saved_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'user_recipe_views', type_='foreignkey')
    op.drop_constraint(None, 'user_recipe_views', type_='foreignkey')
    op.create_foreign_key(op.f('user_recipe_views_recipe_id_fkey'), 'user_recipe_views', 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('user_recipe_views_user_id_fkey'), 'user_recipe_views', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_recipe_views', 'viewed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_recipe_views', 'recipe_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('user_recipe_views', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('units', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('units', 'unit_type',
               existing_type=sa.Enum('WEIGHT', 'VOLUME', 'COUNT', 'OTHER', name='unittype', native_enum=False),
               type_=postgresql.ENUM('weight', 'volume', 'count', 'other', name='unit_type'),
               nullable=False,
               existing_server_default=sa.text("'other'::unit_type"))
    op.drop_index('idx_recipes_uuid', table_name='recipes')
    op.create_index(op.f('idx_recipes_uuid'), 'recipes', ['uuid'], unique=False)
    op.drop_index('idx_recipes_name_desc_fts', table_name='recipes', postgresql_using='gin')
    op.create_index(op.f('idx_recipes_name_desc_fts'), 'recipes', [sa.literal_column("to_tsvector('english'::regconfig, (COALESCE(name, ''::text) || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    op.alter_column('recipes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('recipes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('recipes', 'status',
               existing_type=sa.Enum('DRAFT', 'PUBLISHED', name='recipe_status'),
               type_=sa.VARCHAR(length=20),
               comment='soft draft status: draft | published | archived',
               existing_nullable=False,
               existing_server_default=sa.text("'''draft'''::character varying"))
    op.alter_column('recipe_steps', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('recipe_steps', 'recipe_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('recipe_photos', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('recipe_photos', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('recipe_photos', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('recipe_ingredients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('recipe_ingredients', 'recipe_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint('uq_provider_user', 'oauth_accounts', type_='unique')
    op.create_unique_constraint(op.f('uq_oauth_provider_user'), 'oauth_accounts', ['provider', 'provider_user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('oauth_accounts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('oauth_accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('oauth_accounts', 'provider',
               existing_type=sa.Enum('X', 'GOOGLE', name='oauthprovider', native_enum=False),
               type_=postgresql.ENUM('X', 'GOOGLE', 'local', 'other', name='oauth_provider'),
               existing_nullable=False)
    op.alter_column('ingredients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ingredient_aliases', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('category_groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_recipe_media_type', table_name='recipe_media')
    op.drop_index('idx_recipe_media_recipe_id', table_name='recipe_media')
    op.drop_index('idx_recipe_media_primary', table_name='recipe_media')
    op.drop_index('idx_recipe_media_order', table_name='recipe_media')
    op.drop_table('recipe_media')

    # Drop ENUM types
    postgresql.ENUM(name='storage_provider').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='media_type').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='recipe_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
