"""add_recipe_likes_and_update_saves

Revision ID: e022477fe59c
Revises: 2db19c1c1b59
Create Date: 2026-02-05 18:17:15.128932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e022477fe59c'
down_revision: Union[str, Sequence[str], None] = '2db19c1c1b59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_likes',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('recipe_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'recipe_id')
    )
    op.create_index('idx_recipe_likes_recipe', 'recipe_likes', ['recipe_id'], unique=False)
    op.drop_index(op.f('idx_recipes_name_desc_fts'), table_name='recipes', postgresql_using='gin')
    op.create_index('idx_recipes_name_desc_fts', 'recipes', [sa.literal_column("to_tsvector('english', coalesce(name, '') || ' ' || coalesce(description, '') || ' ' || coalesce(chefs_note, ''))")], unique=False, postgresql_using='gin')
    op.drop_constraint(op.f('user_saved_recipes_user_id_fkey'), 'user_saved_recipes', type_='foreignkey')
    op.drop_constraint(op.f('user_saved_recipes_recipe_id_fkey'), 'user_saved_recipes', type_='foreignkey')
    op.create_foreign_key(None, 'user_saved_recipes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_saved_recipes', 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('users_email_key'), table_name='users')
    op.drop_index(op.f('users_username_key'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('users_username_key'), 'users', ['username'], unique=True)
    op.create_index(op.f('users_email_key'), 'users', ['email'], unique=True)
    op.drop_constraint(None, 'user_saved_recipes', type_='foreignkey')
    op.drop_constraint(None, 'user_saved_recipes', type_='foreignkey')
    op.create_foreign_key(op.f('user_saved_recipes_recipe_id_fkey'), 'user_saved_recipes', 'recipes', ['recipe_id'], ['id'])
    op.create_foreign_key(op.f('user_saved_recipes_user_id_fkey'), 'user_saved_recipes', 'users', ['user_id'], ['id'])
    op.drop_index('idx_recipes_name_desc_fts', table_name='recipes', postgresql_using='gin')
    op.create_index(op.f('idx_recipes_name_desc_fts'), 'recipes', [sa.literal_column("to_tsvector('english'::regconfig, (((COALESCE(name, ''::text) || ' '::text) || COALESCE(description, ''::text)) || ' '::text) || COALESCE(chefs_note, ''::text))")], unique=False, postgresql_using='gin')
    op.drop_index('idx_recipe_likes_recipe', table_name='recipe_likes')
    op.drop_table('recipe_likes')
    # ### end Alembic commands ###
